env: dev

vault:
  enabled: true

ingress:
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: tag-cpm-pipelinetesting-service-ingress-branchname
    annotations:
      nginx.org/server-tokens: 'false'
  spec:
    tls:
      hosts:
        local-pricing-pipelinetesting.np-k8s.sherwin.com
    rules:
      host: local-pricing-pipelinetesting.np-k8s.sherwin.com
      http:
        paths:
          path: /
          pathType: Prefix
          backend:
            service:
              name: tag-cpm-pipelinetesting-service-svc-branchname
              port:
                number: 8080
