name: Example Workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: echo "Branch name is ${GITHUB_REF#refs/heads/}"
