name: Example Workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        env: 
          BRANCH_NAME: ${{ github.ref }}
        run: |
          if [[ "$BRANCH_NAME" =~ refs/heads/ ]]; then
            BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          fi
          sed -i "s|branchname|${BRANCH_NAME}|g" values.yaml || { echo "Error: Failed to update values.yaml"; exit 1; }
          ls -la
          cat values.yaml
