name: Example Workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        env: 
          BRANCH_NAME: ${{ github.ref }}
        run: |
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          echo $BRANCH_NAME
