name: Example Workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        env: 
          BRANCH_NAME: ${GITHUB_REF#refs/heads/}
        run: |
          sed -i "s/branchname/$BRANCH_NAME/g" values.yaml
          ls -la
          cat values.yaml
