name: Example Workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check branch name
        run: echo "Branch name is ${{ github.head_ref }}"
